

services:
  postgres:
    image: postgres:15
    container_name: home-admin-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: home_admin
    ports:
      - "5540:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/home_admin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

